version: '3'
services:

  redis:
    image: "redis:alpine"

  authors:
    image: bff-authors-service:latest
    container_name: bff-authors-service
    depends_on:
      - redis

  books:
    image: bff-books-service:latest
    container_name: bff-books-service
    depends_on:
      - redis

  frontend:
    image: bff-frontend-service:latest
    container_name: bff-frontend-service
    depends_on:
      - books
      - authors
  
  notifications:
    image: bff-push-service:latest
    container_name: bff-push-service
    depends_on:
      - redis

  api-gateway:
    image: bff-api-gateway:latest
    container_name: bff-api-gateway
    ports:
       - 8080:80
    depends_on:
      - authors
      - books
      - notifications
    environment:
      - AUTH_TOKEN=test123323testtoken

  web_app:
    image: web-client:latest
    container_name: web-client
    environment:
      - AUTHORS_AUTH_TOKEN=test123323testtoken
      - CLIENT_TYPE=WEB
    depends_on:
      - api-gateway

  mobile_app:
    image: mobile-client:latest
    container_name: mobile-client
    environment:
      - AUTHORS_AUTH_TOKEN=test123323testtoken
      - CLIENT_TYPE=MOBILE
    depends_on:
      - api-gateway
